### ISSUE TITLE
Allow lower case map names

### ISSUE THREAD

**Issue by wesleywerner** [gamescomputersplay/wad2pic#3]
Map names should be automatically made uppercase, as it can trip up some users.

https://github.com/gamescomputersplay/wad2pic/blob/e8612bdcd2a61ca8b24d39012ef7cdbc52d831e7/wad2pic.py#L2378

```
map = docOptions["<map>"].upper()
```

**Comment by gamescomputersplay** [comment]
Updated, thanks!
